### ISSUE TITLE
Wrong Media File interrupts whole synchronisation

### ISSUE THREAD

**Issue by t177p** [studip-sync/studip-sync#10]
If there is one wrong Media file in any Lecture (so attached image - in this case it seems to be an m4a file for download only), than the whole synchronisation process interrupts und not a single file gets synced.

Is there a way to fix this or at least a way to skip one course while syncing?
![Bildschirmfoto 2021-06-04 um 13 00 50](https://user-images.githubusercontent.com/58940503/120791765-e53ec700-c534-11eb-8729-0da8cb094fe7.png)

**Comment by lenke182** [comment]
Can you post the error that happens when it tries to download the m4a file?

Yes, it is possible to skip all errors and download the next course/file. As some errors (due to misconfiguration or changes to StudIP) will occur in all courses / files, I wouldn't want to skip a course on any error only specific types of errors.

**Comment by t177p** [comment]
`Traceback (most recent call last):
  File "/Users/till/studip-sync/studip_sync.py", line 29, in <module>
    exit(s.sync(ARGS.full, ARGS.recent))
  File "/Users/till/studip-sync/studip_sync/studip_sync.py", line 96, in sync
    session.download_media(course["course_id"], media_course_dir, course["save_as"])
  File "/Users/till/studip-sync/studip_sync/session.py", line 174, in download_media
    media_files = parsers.extract_media_list(response.text)
  File "/Users/till/studip-sync/studip_sync/parsers.py", line 159, in extract_media_list
    raise ParserError("media_list: a_element is missing")
studip_sync.parsers.ParserError: media_list: a_element is missing
Done!
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.`

**Comment by lenke182** [comment]
Added support for direct download media files in 04a38ad7

Please review if studip-sync now correctly downloads the media file.
