### ISSUE TITLE
Cannot access SSO server

### ISSUE THREAD

**Issue by cormensratio** [studip-sync/studip-sync#11]
Using studip-sync fails with the following output:

`Logging in...`
`Login failed!`
`Cannot access SSO server`

I use the snap package with the `University of Passau` server.

**Comment by tionis** [comment]
I also have this issue, also in Passau

**Comment by lenke182** [comment]
It seems like there have been some updates to the SSO server structure that break the current implementation.
I added some debug statements in 84f8791d9f0df72b0d703bc47f220e32bf8b6f13.
They won't solve the problem but give me enough information to fix the problem as I'm not at the University of Passau.
Please either download the commit via git (or if you are using snap, wait until snap builds and publishes a new version) and then execute `studip-sync -v` with the verbose flag. Please copy the full output and post it here so I can fix the issue.

**Comment by david-schr** [comment]
Thanks for the debug statements.

They introduced a hidden **csrf_token** field  in the Login form, which needs to be sent in the POST reqeuest.
It can be extracted in the same way as the SAML data after the request on the "login_url"

The relevant section from the Login form page:
```html
<form action="/idp/profile/SAML2/Redirect/SSO?execution=e4s1" method="post">
<input type="hidden" name="csrf_token" value="_a18f1b316a28577e6a97d119e6e2ee0477ef4e11" />
```

The POST data:
```
csrf_token	"_a18f1b316a28577e6a97d119e6e2ee0477ef4e11"
j_username	"xxx"
j_password	"xxx"
donotcache	"1"
_eventId_proceed	""
```

**Comment by lenke182** [comment]
@cormensratio @tionis Please review if the change in #12 fixed the error.

**Comment by tionis** [comment]
Seems to be working for me, thanks!

**Comment by lenke182** [comment]
Great!

**Comment by cormensratio** [comment]
Thank you for the quick response and fix. It is working for me 👍🏽.
