### ISSUE TITLE
Download Documents: extraction error in non-new / non-rsync mode

### ISSUE THREAD

**Issue by JayCeM** [studip-sync/studip-sync#14]
On one course I get following error message:
```Extracting files failed: Cannot extract file /tmp/studip-sync8i_8jose/zips/d4430f4f8a6b083```
I did some research, and the problem is that the media files of this course are *"incorrectly"* uploaded to the Documents section, not the Media section of the course.
Therefore studip-sync attempts to download a very big zip-file which exceeds the StudIP limit of ```524288000 bytes```.
In rsync mode (```--new```) the error does not occur.

I suggest using rsync mode as the default, and offering sync mode via ```--old```, as it may not be clear to every user that an rsync mode even exists (I only found out besause of this error).

**Comment by lenke182** [comment]
Yes, I agree. I have changed the default behaviour in eba01f20b87be9ef14c737a7ee75ad8c7b61212b.

The rsync client was unstable in the beginning and didn't work with every filetype. But now it performs a lot better than the older code.
