### ISSUE TITLE
pipx upgrade not working

### ISSUE THREAD

**Issue by barkawa** [studip-sync/studip-sync#27]
`$ pipx upgrade studip-sync`
`studip-sync is already at latest version 2.0.0 (location: /Users/vogel/.local/pipx/venvs/studip-sync)`

Maybe bump the version on every commit, so it upgrades correctly

**Comment by lenke182** [comment]
I setup a pre-push hook in .git now: 449a7cc1e4478df382f8035a66570f5cf4214985
