### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by lenke182** [studip-sync/studip-sync#3]
Just saw your message about a new maintainer for this project.

I have been already maintaining studip-sync the last year or so in my fork of this project [1] to support the University of Göttingen and added a lot of further features. So I'd be happy to maintain this project since I use it regularly. 

[1] https://github.com/lenke182/studip-sync

**Comment by woefe** [comment]
Cool :+1:  You already have a fork of this repo on your account. According to the [docs](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository) it's not possible to transfer a repo if the receiver has a fork or a repo of the same name in their account.

I created a GitHub org and will transfer the repo and add you as maintainer.

**Comment by woefe** [comment]
@lenke182 Org is created and you are invited to join.

**Comment by lenke182** [comment]
Great. Thanks.
