### ISSUE TITLE
[Bug] Login no longer working for university passau

### ISSUE THREAD

**Issue by tionis** [studip-sync/studip-sync#6]
If trying to login using "https://studip.uni-passau.de" as base URL I only get following error message:
```
login: Couldn't find login data! Is the base url correct?
```

**Comment by lenke182** [comment]
I added new functionality to handle different authentication methods in https://github.com/studip-sync/studip-sync/commit/e4d1e0db3fb7ca663c80feb32da69d8ce1fc8ef3.

Please retry by executing `studip-sync --init` and selecting the second preset. 

If you get a ParserError with `Could not parse SAML form` someone will need to fix `ShibbolethLogin.extract_saml_data(html)`  in `studip_sync/logins/shibboleth.py` because I don't have an account at the University of Passau and therefore can't test if this functionality still works.

**Comment by tionis** [comment]
With the new commits i now get a `ModuleNotFoundError: No module named 'studip_sync.logins'` error when trying to `studip-sync --init`

**Comment by lenke182** [comment]
Do you run studip-sync as snap or from the source?

Also please post the full stack trace of the error, so I can fix it.

**Comment by tionis** [comment]
I'm running on the AUR version on linux. The issue as lined out in my previous comment was fixed, but I encountered the error as you predicted:
```
Traceback (most recent call last):
  File "/usr/bin/studip-sync", line 9, in <module>
    creator.new_config()
  File "/usr/lib/python3.8/site-packages/studip_sync/config_creator.py", line 89, in new_config
    self._session.login(auth_key, auth_data, username, password)
  File "/usr/lib/python3.8/site-packages/studip_sync/session.py", line 85, in login
    auth.login(self, username, password, auth_type_data)
  File "/usr/lib/python3.8/site-packages/studip_sync/logins/shibboleth.py", line 29, in login
    saml_data = ShibbolethLogin.extract_saml_data(response.text)
  File "/usr/lib/python3.8/site-packages/studip_sync/logins/shibboleth.py", line 48, in extract_saml_data
    "RelayState": _extract_value("RelayState"),
  File "/usr/lib/python3.8/site-packages/studip_sync/logins/shibboleth.py", line 43, in _extract_value
    raise ParserError("Could not parse SAML form")
studip_sync.parsers.ParserError: Could not parse SAML form
```

**Comment by lenke182** [comment]
I'm assuming the Sibboleth SSO was changed some time ago and the `RelayState` and `SAMLResponse` data are stored differently in the html response.

You can either provide me the html response of that request (which may contain sensitive information) so I can fix that function, fix it yourself or wait for another person with an account at the University of Passau to fix it.

**Comment by tionis** [comment]
@lenke182 Yeah I figured as much, how can I send you the response privately?

**Comment by lenke182** [comment]
I just went over the shibboleth authentication flow and found some errors, so please retry with the new commits in `master`.

If this doesn't work, I'll send you an email with the relevant instructions.

**Comment by tionis** [comment]
Thanks, The latest changes fixed the login issue!
But when trying to download the courses now (by executing without arguments) a new issue arises:  
Do you want to track this in this issue?
```
Logging in...
Downloading course list...
1) WiSe 20/21: MY_COURSE_NAME
Traceback (most recent call last):
  File "/usr/bin/studip-sync", line 29, in <module>
    exit(s.sync(ARGS.full, ARGS.recent))
  File "/usr/lib/python3.8/site-packages/studip_sync/studip_sync.py", line 73, in sync
    if sync_fully or session.check_course_new_files(course["course_id"], CONFIG.last_sync):
  File "/usr/lib/python3.8/site-packages/studip_sync/session.py", line 103, in check_course_new_files
    last_edit = parsers.extract_files_flat_last_edit(response.text)
  File "/usr/lib/python3.8/site-packages/studip_sync/parsers.py", line 17, in extract_files_flat_last_edit
    if not "data-files" in form.attrs:
AttributeError: 'NoneType' object has no attribute 'attrs'

```

**Comment by lenke182** [comment]
We can track it in this issue.

If I researched this correctly, the University of Passau uses StudIP 4.5.1.3 instead of 4.6.0.1. In 4.6 there were some pretty significant changes in the way the files are handled and stored in the html. To fix this I would need to rework larger parts of the parser code.

But you could also try using `studip-sync --full`. This will skip this specific request to check if new files are present and therefore always download all data.

**Comment by lenke182** [comment]
I realized there is an easier way to support both versions: 179af5c2

Please retry.

**Comment by tionis** [comment]
Thanks, it seems to be working now! It runs trough downloading all the new files.
On a side note, I get following error message, but I'm pretty sure it appears because no course has actual videos uploaded in studip.
```
Download of media failed: Cannot access mediacast list page
```

**Comment by lenke182** [comment]
> On a side note, I get following error message, but I'm pretty sure it appears because no course has actual videos uploaded in studip.
> 
> ```
> Download of media failed: Cannot access mediacast list page
> ```
This just means that the `mediacast` plugin isn't activated for that course. And since studip-sync can't know if this plugin is knowingly deactivated or the plugin produces an error, it just logs that occurance.
