### ISSUE TITLE
[Feature Request] Integrate support of password manager

### ISSUE THREAD

**Issue by tionis** [studip-sync/studip-sync#7]
Allow usage of password managers likes GNU pass.  
In practice this means there should be an extra field in the json that if set describes an command that outputs the password via stdout.
e.g. for pass
```json
{
  "pass-command": "pass university/studip"
}
```
or for bitwarden cli:
```json
{
  "pass-command": "bw get password dc309fc8-3f2e-416e-9eb2-ab90015912c6"
}
```

**Comment by lenke182** [comment]
Added `password_command` to config in afe196fc

Please review if this works for your use case.

Your config should look like this:
```
{
    "user": {
        "login": "bob",
        "password_command": "echo 123456"
    },
    ...
}
```

**Comment by tionis** [comment]
Awesome, it works perfectly.  
Thanks!
